[package]
name = "opengl_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#glutin = "0.28.0"
glium = { version = "*", default-features = true }
cgmath = "0.18"
parking_lot = "0.11"
