[package]
name = "opengl_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[example]]
name = "example"
path = "examples/example.rs"

[[example]]
name = "sphere_grid"
path = "examples/sphere_grid.rs"

[dependencies]
#glutin = "0.28.0"
glium = { version = "*", default-features = true }
cgmath = "0.18"
parking_lot = "0.11"
tobj = "3.2.0"
russimp = "1.0.1"
image = "0.23.14"
gl = "0.14.0"
